version: '3.8'

services:
  react-app:
    image: gogi4a/myfriend
    ports:
      - "80:80"
    depends_on:
      - node-app

  node-app:
    image: gogi4a/myfriendbe
    ports:
      - "8080:3000"
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'MyFriend'
      MYSQL_ROOT_PASSWORD: 'random-Password1'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: